### ISSUE TITLE
idSite feature available? 

### ISSUE THREAD

**Issue by deanmraz** [stormpath/stormpath-lumen#1]
I've enabled it but none of the routes work

idSite:
    enabled: true
    uri: "/idSiteResult"
    nextUri: "/"
    loginUri: "/login"
    forgotUri: "/forgot"
    registerUri: "/register"

**Comment by bretterer** [comment]
@deanmraz 

I am sorry for the confusion here.  idSite is a web based flow and is not set up to function inside of the stormpath-lumen package.  

The stormpath-lumen package is designed to only respond with JSON responses.  If you are looking to use idSite with one of our integrations, you would have to switch to using stormpath-laravel package inside of Laravel.  (the stormpath-laravel package will not work with Lumen)

I will make a note here to remove the idSite configuration options from the yaml file.

**Comment by bretterer** [comment]
Resolved and will be released in 0.1.4

Will require re-publishing config file, or removing that section.
