### ISSUE TITLE
accountStores array response incorrectly structured?

### ISSUE THREAD

**Issue by JunkMyFunk** [stormpath/stormpath-lumen#2]
I receive an error from the Stormpath AngularJS login controller when integrating with the Stormpath Lumen API. The error from Angular is `Cannot read property 'providerId' of undefined`

When examining the response generated by `LoginController::respondWithForm()` method, it seems the `accountStores` array contains an unexpected nested array.

Actual response:
![actual response](https://cloud.githubusercontent.com/assets/2786106/15852754/b5193bda-2ca2-11e6-81ca-eb30e3e1f5d9.png)

Expected response (without nested array)
![expected response](https://cloud.githubusercontent.com/assets/2786106/15852753/b50f54c6-2ca2-11e6-8043-bf3e5d6dec89.png)

Problem appears to be caused at `src/Http/Controllers/LoginController.php:138` where the get from cache is wrapped in an array.

**Comment by bretterer** [comment]
Thank you for this report.   I see the PR that you submitted,  I am going to modify a few items in that that relate to https://github.com/stormpath/stormpath-laravel/pull/48.  This will be merged in soon.

**Comment by bretterer** [comment]
Resolved in PR #3 

Will be released in 0.1.4
