### ISSUE TITLE
StormpathServiceProvider does not add provider as part of accountStoresArray

### ISSUE THREAD

**Issue by JunkMyFunk** [stormpath/stormpath-lumen#4]
LoginController and RegisterController return an array of accountStores which only includes the account store `name` and `href` properties and does not include the `provider` property with the provider `href` and `providerId`.

This issue seems to have been introduced [here](https://github.com/stormpath/stormpath-lumen/commit/7be8e944fd9580debf11c58b2304ea12aeeb831f#diff-024729bee620ae79709af24159f682beR234) as the `Stormpath\Resource\Provider` class which is set to `$mapping->accountStore` uses a property object and magic methods to store property values, which does not make values accessible to `isset()`, so this will always evaluate to false.

**Comment by bretterer** [comment]
@JunkMyFunk Thanks for mentioning this.  I will push a bugfix ASAP

Brian

**Comment by bretterer** [comment]
@JunkMyFunk Justed wanted to touch base with you to make sure you see the updates that were made.  The register and login get requests now provide the account stores with provider object

-Brian
